# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml
      - /gitlab-templates/reuse-lint.yml

.yocto_base:
  stage: build
  image: invent-registry.kde.org/sysadmin/ci-images/yocto-builder:latest
  tags:
    - Yocto
  before_script:
    - repo init -u https://invent.kde.org/packaging/yocto-manifest.git -m scarthgap.xml
    - repo sync
  after_script:
    - cp build-visionfive2/tmp/log/cooker/visionfive2/console-latest.log bitbake.log
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - build-visionfive2/tmp/buildstats/
      - bitbake.log

yocto_scarthgap:
  extends: .yocto_base
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
  script:
    - MACHINE=visionfive2 . ./setup-environment
    - echo 'SSTATE_MIRRORS = "file://.* file:///mnt/caches/yocto_sstate_scarthgap/PATH"' >> conf/site.conf
# limit computation: ncpus/4
    - echo 'BB_NUMBER_THREADS = "4"' >> conf/site.conf
    - echo 'OMP_NUM_THREADS = "4"' >> conf/site.conf
    - bitbake packagegroup-kf6-full

yocto_scarthgap_seeding:
  extends: .yocto_base
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - MACHINE=visionfive2 . ./setup-environment
    - echo 'SSTATE_DIR = "/mnt/caches/yocto_sstate_scarthgap"' >> conf/site.conf
# limit computation: ncpus/4
    - echo 'BB_NUMBER_THREADS = "4"' >> conf/site.conf
    - echo 'OMP_NUM_THREADS = "4"' >> conf/site.conf
    - bitbake packagegroup-kf6-full

qa_testing:
  stage: test
  image: invent-registry.kde.org/sysadmin/ci-images/yocto-builder:latest
  script:
    - cat bitbake.log | grep -E "WARNING:|ERROR:" > bitbake.error
    - "if [[ $(cat bitbake.error | grep 'WARNING:' -i) ]]; then cat bitbake.error; exit 1; fi"
  allow_failure: true
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - bitbake.error
