# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml
      - /gitlab-templates/reuse-lint.yml

lint:oelint:
  tags:
    - Linux
  stage: validate
  image: python:3.11-slim
  before_script:
    - pip install --upgrade pip
    - pip install oelint-adv
  script:
    - ./scripts/run_oelintadv.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

.yocto_base_scarthgap:
  stage: build
  image: storage.kde.org/vm-images/yocto-builder-noble
  tags:
    - LargeVM
    - amd64
  before_script:
# generic sysadmin tooling
    - pip3 install --break-system-packages minio
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
# Yocto Repo setup
    - repo init -u https://invent.kde.org/packaging/yocto-manifest.git -m scarthgap.xml
# Inject merge request override if needed
    - |
      if [[ -n "$CI_MERGE_REQUEST_IID" ]]; then
        echo "Applying MR override for meta-kf6"

        mkdir -p .repo/local_manifests

        cat > .repo/local_manifests/meta-kf6-mr.xml <<EOF
      <manifest>
      <extend-project name="yocto-meta-kf6"
              revision="refs/merge-requests/${CI_MERGE_REQUEST_IID}/head"/>
      </manifest>
      EOF
      fi
    - repo sync -j$(nproc)
  after_script:
    - cp -L build-visionfive2/tmp/log/cooker/visionfive2/console-latest.log bitbake.log
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - build-visionfive2/tmp/buildstats/
      - bitbake.log

yocto_scarthgap:
  extends: .yocto_base_scarthgap
  rules:
    - if: '$CI_COMMIT_BRANCH != "scarthgap" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "scarthgap"'
  script:
    - MACHINE=visionfive2 . ./setup-environment
# workaround for scarthgap CI, because meta-kde does not support scarthgap but only one bblayers file is shared
    - sed -i 's|${BSPDIR}/sources/meta-kde | |g' conf/bblayers.conf
    - echo 'SSTATE_MIRRORS += "file://.* file:///mnt/yocto_sstate_scarthgap/PATH"' >> conf/site.conf
    - echo 'SSTATE_MIRRORS += "file://.* https://storage.kde.org/yocto-sstate/scarthgap/PATH;downloadfilename=PATH"' >> conf/site.conf
    - echo 'INHERIT += "rm_work"' >> conf/site.conf
# limit computation: ncpus/4
    - echo 'BB_NUMBER_THREADS = "4"' >> conf/site.conf
    - echo 'OMP_NUM_THREADS = "4"' >> conf/site.conf
    - bitbake packagegroup-kf6-full

yocto_scarthgap_seeding:
  extends: .yocto_base_scarthgap
  rules:
    - if: $CI_COMMIT_BRANCH == "scarthgap"
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  script:
    - MACHINE=visionfive2 . ./setup-environment
# workaround for scarthgap CI, because meta-kde does not support scarthgap but only one bblayers file is shared
    - sed -i 's|${BSPDIR}/sources/meta-kde | |g' conf/bblayers.conf
# host local cache: for sstate sharing without hash equiv server only basic hash works
    - echo 'BB_HASHSERVE = ""' >> conf/site.conf
    - echo 'BB_SIGNATURE_HANDLER = "OEBasicHash"' >> conf/site.conf
    - echo 'SSTATE_MIRRORS += "file://.* https://storage.kde.org/yocto-sstate/scarthgap/PATH;downloadfilename=PATH"' >> conf/site.conf
    - echo 'SSTATE_DIR = "/mnt/yocto_sstate_scarthgap"' >> conf/site.conf
    - echo 'INHERIT += "rm_work"' >> conf/site.conf
# limit computation: ncpus/4
    - echo 'BB_NUMBER_THREADS = "4"' >> conf/site.conf
    - echo 'OMP_NUM_THREADS = "4"' >> conf/site.conf
    - bitbake packagegroup-kf6-full
# upload to shared sstate storage
    - ${CI_PROJECT_DIR}/ci-utilities/sync-s3-folder.py --mode upload --local /mnt/yocto_sstate_scarthgap --remote storage.kde.org/yocto-sstate/scarthgap/ --verbose

.yocto_base_wrynose:
  stage: build
  image: storage.kde.org/vm-images/yocto-builder-noble
  tags:
    - LargeVM
    - amd64
  before_script:
# generic sysadmin tooling
    - pip3 install --break-system-packages minio
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
# prepare bitbake
    - |
        [ -d /mnt/yocto_sstate_wrynose ] || mkdir -p /mnt/yocto_sstate_wrynose
    - git clone --depth 1 --branch yocto-6.0 https://github.com/openembedded/bitbake.git
    - |
    - |
        ./bitbake/bin/bitbake-setup init \
            --non-interactive \
            --source-overrides scripts/ci/gitlab-source-override.json \
            scripts/ci/kde-master.conf.json \
            kde \
            distro/poky machine/beaglev-ahead
  after_script:
    - cp -L ./bitbake-builds/poky-master/tmp/log/cooker/beaglev-ahead/console-latest.log bitbake.log
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - ./bitbake-builds/poky-master/build/tmp/buildstats/
      - bitbake.log

yocto_wrynose:
  extends: .yocto_base_wrynose
  timeout: 8 hours
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - source bitbake-builds/poky-master/build/init-build-env
    - bitbake-config-build enable-fragment kf6/autobuilder kf6/sstate_wrynose
    - bitbake packagegroup-kf6-full

yocto_wrynose_seeding:
  extends: .yocto_base_wrynose
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  id_tokens:
    MINIO_OIDC:
      aud: https://tokens.kde.org
  script:
    - source bitbake-builds/poky-master/build/init-build-env
    - bitbake-config-build enable-fragment kf6/autobuilder kf6/sstate_wrynose_seeding
    - bitbake packagegroup-kf6-full
# cleanup local sstate cache before upload
    - ${CI_PROJECT_DIR}/bitbake-builds/poky-master/layers/openembedded-core/scripts/sstate-cache-management.py --remove-duplicated --cache-dir /mnt/yocto_sstate_wrynose --verbose --yes
# upload to shared sstate storage
    - ${CI_PROJECT_DIR}/ci-utilities/sync-s3-folder.py --mode upload --local /mnt/yocto_sstate_wrynose --remote storage.kde.org/yocto-sstate/wrynose/ --verbose

qa_testing:
  stage: test
  image: invent-registry.kde.org/sysadmin/ci-images/yocto-builder:latest
  script:
    - |-
        cat bitbake.log | grep -E "WARNING:|ERROR:" | grep -v "You are using a local hash equivalence server but have configured an sstate mirror" > bitbake.error || true
        if [[ -s bitbake.error ]]; then
            echo "Bitbake warnings detected:"
            cat bitbake.error
            exit 1
        else
            echo "No warnings detected"
        fi
  allow_failure: true
  artifacts:
    expire_in: 3 days
    when: always
    paths:
      - bitbake.error
