# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

DEPENDS:remove:pn-kguiaddons = "${@'qtwayland-native' if bb.utils.vercmp_string_op(d.getVar('QT_VERSION') or '', '6.10.0', '>=') else ''}"
DEPENDS:remove:pn-kidletime = "${@'qtwayland-native' if bb.utils.vercmp_string_op(d.getVar('QT_VERSION') or '', '6.10.0', '>=') else ''}"
DEPENDS:remove:pn-kwindowsystem = "${@'qtwayland-native' if bb.utils.vercmp_string_op(d.getVar('QT_VERSION') or '', '6.10.0', '>=') else ''}"
DEPENDS:remove:pn-plasma-wayland-protocols = "${@'qtwayland-native' if bb.utils.vercmp_string_op(d.getVar('QT_VERSION') or '', '6.10.0', '>=') else ''}"
